import { DocumentTextIcon } from '@sanity/icons/DocumentText'
import { ImageIcon } from '@sanity/icons/Image'
import { UserIcon } from '@sanity/icons/User'
import { defineArrayMember, defineField, defineType } from 'sanity'

const image = (title = 'Image', name = 'image') => defineField({ name, title, type: 'image', options: { hotspot: true } })
const legacyImagePath = (name = 'imagePath') => defineField({ name, type: 'string', title: 'Previous image path', hidden: true, readOnly: true, deprecated: { reason: 'Upload or select an image using the Image field above.' } })
const text = (name: string, title: string) => defineField({ name, title, type: 'text', rows: 3 })
const common = [defineField({ name: 'eyebrow', type: 'string' }), defineField({ name: 'heading', type: 'string' }), text('description', 'Description')]

export const heroSection = defineType({ name: 'heroSection', title: 'Hero', type: 'document', icon: DocumentTextIcon, fields: [...common, image('Hero image'), legacyImagePath(), defineField({ name: 'stats', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'value', type: 'string' }), defineField({ name: 'label', type: 'string' })] })] })], preview: { prepare: () => ({ title: 'Hero' }) } })
export const aboutSection = defineType({ name: 'aboutSection', title: 'About hospital', type: 'document', icon: DocumentTextIcon, fields: [...common, defineField({ name: 'values', title: 'Care values', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'title', type: 'string', validation: (rule) => rule.required() }), text('description', 'Description')] })] }), defineField({ name: 'founderName', type: 'string' }), text('founderDescription', 'Founder description'), image('Founder portrait', 'founderImage'), legacyImagePath('founderImagePath')], preview: { prepare: () => ({ title: 'About hospital' }) } })
export const teamSection = defineType({ name: 'teamSection', title: 'Team', type: 'document', icon: UserIcon, fields: [...common, defineField({ name: 'members', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'name', type: 'string', validation: (rule) => rule.required() }), defineField({ name: 'role', type: 'string' }), defineField({ name: 'qualifications', type: 'string' }), defineField({ name: 'specialties', type: 'array', of: [defineArrayMember({ type: 'string' })] }), image('Portrait image'), legacyImagePath()] })] })], preview: { prepare: () => ({ title: 'Team' }) } })
export const servicesSection = defineType({ name: 'servicesSection', title: 'Services', type: 'document', icon: DocumentTextIcon, fields: [...common, defineField({ name: 'featured', title: 'Featured services', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'title', type: 'string' }), text('description', 'Description'), image('Service image'), legacyImagePath()] })] }), defineField({ name: 'additional', title: 'Additional services', type: 'array', of: [defineArrayMember({ type: 'string' })] })], preview: { prepare: () => ({ title: 'Services' }) } })
export const technologySection = defineType({ name: 'technologySection', title: 'Technology', type: 'document', icon: DocumentTextIcon, fields: [...common, defineField({ name: 'machines', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'name', type: 'string' }), text('description', 'Description'), image('Machine image'), legacyImagePath()] })] })], preview: { prepare: () => ({ title: 'Technology' }) } })
export const gallerySection = defineType({ name: 'gallerySection', title: 'Gallery', type: 'document', icon: ImageIcon, fields: [...common, defineField({ name: 'items', type: 'array', of: [defineArrayMember({ type: 'object', fields: [image(), legacyImagePath(), defineField({ name: 'alt', type: 'string' })] })] })], preview: { prepare: () => ({ title: 'Gallery' }) } })
export const communitySection = defineType({ name: 'communitySection', title: 'Community outreach', type: 'document', icon: ImageIcon, fields: [...common, defineField({ name: 'items', title: 'Camp photos', type: 'array', of: [defineArrayMember({ type: 'object', fields: [image(), legacyImagePath(), defineField({ name: 'alt', type: 'string' })] })] }), defineField({ name: 'footerText', title: 'Footer text', type: 'string' })], preview: { prepare: () => ({ title: 'Community outreach' }) } })
export const videosSection = defineType({ name: 'videosSection', title: 'Clinic videos', type: 'document', icon: DocumentTextIcon, fields: [...common, defineField({ name: 'items', title: 'Videos', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'title', type: 'string', validation: (rule) => rule.required() }), defineField({ name: 'video', title: 'Video file', type: 'file', options: { accept: 'video/*' } }), defineField({ name: 'videoPath', title: 'Previous video path', type: 'string', hidden: true, readOnly: true, deprecated: { reason: 'Use the Video file upload field.' } })] })] })], preview: { prepare: () => ({ title: 'Clinic videos' }) } })
export const mediaSection = defineType({ name: 'mediaSection', title: 'Media', type: 'document', icon: ImageIcon, fields: [defineField({ name: 'items', type: 'array', of: [defineArrayMember({ type: 'object', fields: [image(), legacyImagePath(), defineField({ name: 'alt', type: 'string' })] })] })], preview: { prepare: () => ({ title: 'Media' }) } })
export const testimonialsSection = defineType({ name: 'testimonialsSection', title: 'Testimonials', type: 'document', icon: DocumentTextIcon, fields: [...common, image('Feature image', 'featuredImage'), legacyImagePath('featuredImagePath'), defineField({ name: 'imageLabel', type: 'string' }), defineField({ name: 'items', type: 'array', of: [defineArrayMember({ type: 'object', fields: [text('quote', 'Quote'), defineField({ name: 'name', type: 'string' }), defineField({ name: 'detail', type: 'string' })] })] })], preview: { prepare: () => ({ title: 'Testimonials' }) } })
export const contactSection = defineType({ name: 'contactSection', title: 'Contact', type: 'document', icon: DocumentTextIcon, fields: [...common, image('Appointment image', 'appointmentImage'), legacyImagePath('appointmentImagePath'), defineField({ name: 'phoneNumbers', type: 'array', of: [defineArrayMember({ type: 'string' })] }), defineField({ name: 'email', type: 'string', validation: (rule) => rule.email() }), defineField({ name: 'hours', type: 'string' }), text('address', 'Address')], preview: { prepare: () => ({ title: 'Contact' }) } })
export const footerSection = defineType({ name: 'footerSection', title: 'Footer', type: 'document', icon: DocumentTextIcon, fields: [text('description', 'Clinic description'), defineField({ name: 'treatmentLinks', title: 'Treatment links', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'label', type: 'string' }), defineField({ name: 'href', type: 'string' })] })] }), defineField({ name: 'exploreLinks', title: 'Explore links', type: 'array', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'label', type: 'string' }), defineField({ name: 'href', type: 'string' })] })] }), text('address', 'Address'), defineField({ name: 'phone', type: 'string' }), defineField({ name: 'email', type: 'string', validation: (rule) => rule.email() }), defineField({ name: 'hours', type: 'string' }), defineField({ name: 'copyright', type: 'string' })], preview: { prepare: () => ({ title: 'Footer' }) } })

export const sectionTypes = [heroSection, aboutSection, teamSection, servicesSection, technologySection, gallerySection, communitySection, videosSection, mediaSection, testimonialsSection, contactSection, footerSection]
